# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/barloff2/python/blob/udemy/pandas.ipynb

# **Práctica de la librería Pandas**
Es como un excel de python
"""
# Importar os
from os import system
import pandas as pd

system('cls')
# Creamos una serie de números y hallamos su media
numeros = pd.Series([1, 2, 3, 4, 5, 57, 223, 99, 47])
numeros.mean()

# Hallamos la suma de dichos números
numeros.sum()

# Creamos una SERIE de tres colores diferentes
colores = pd.Series(['rojo', 'amarillo', 'verde'])

# Visualizamos la serie Creada
colores

# Creamos una serie con tipos de autos, y la vosualizamos
tipos_autos = pd.Series(['sedan', 'SUV', 'Pick Up'])
tipos_autos

# Combinamos las sires de tipo de autos y colores en un DATAFRAME
tabla_autos = pd.DataFrame({'Tipo de Auto': tipos_autos, 'Color': colores})
tabla_autos

# Importar "ventas-autos.csv" y convertirlo en un nuevo DATAFRAME

ventas_autos = pd.read_csv("ventas-autos.csv")
print(ventas_autos)

'''Este será nuestro "Dataframe del flujo vehicular"'''

# Exportar el dataframe como un archivo csv a mi carpeta diferente
#ventas_autos.to_csv("ventas-autos-exportado.csv")

# Analicemos los tipos de datos disponibles en el dataset de ventas autos
print(ventas_autos.dtypes)

# Aplicamos estadística descriptiva (cantidad de valores, media, desviación estándar, valores mínimos y máximos, cuartiles) al dataset
print(ventas_autos.describe())

# Obtenemos información del dataset utilzado info()
print(ventas_autos.info())

# Listamos los nombres de las columnas de nuestro dataset
print(ventas_autos.columns)

# Averiguamos el "largo" de nuestro dataset
print(len(ventas_autos))

# Mostramos las primeras 5 filas del dataset
print(ventas_autos.head())

# Mostramos las primeras 7 filas del dataset
print(ventas_autos.head(7))

# Mostramos las últimas 5 filas del dataset
print(ventas_autos.tail())

# Utilizamos .loc para seleccionar la fila de indice 3 del dataframe
print(ventas_autos.loc[3])

# Utilizamos .iloc para seleccionar las filas 3, 7 y 9
print(ventas_autos.iloc[[3, 7, 9]])

'''Documentación https://www.datacamp.com/es/tutorial/loc-vs-iloc'''

system('cls')

# Seleccionar la columna "Kilometraje"
print(ventas_autos["Kilometraje"])

# Encontrar el valor medio de las columnas "Kilometraje"
print(ventas_autos["Kilometraje"].mean())

# Seleccionar aquellas columnas que tengan valores superiores a 100,000 kilómetros en la columna Kilometraje
print(ventas_autos[ventas_autos["Kilometraje"] > 100000])

# Creamos una tabla cruzada de doble entrada entre Fabricante y cantidad de puertas
tabla_cruzada = pd.crosstab(ventas_autos["Fabricante"], ventas_autos["Puertas"])
print(tabla_cruzada)

# Agrupamos las columnas por fabricante y buscando el valor medio de las columnas numéricas
agrupado = ventas_autos.groupby(["Fabricante"]).mean(numeric_only=True)
print(agrupado)

# Importamos MatPlotlib y creamos un gráfico con los valores de la columna Kilometraje
system('cls')
import matplotlib.pyplot as plt

ventas_autos['Kilometraje'].plot()
plt.title('Kilometraje de Vehículos')
plt.ylabel('Kilometraje')
plt.xlabel('Índice')
plt.show()

# Puede que un gráfico más apropiado en este caso sea un histograma
ventas_autos['Kilometraje'].hist()
plt.title('Distribución de Kilometraje')
plt.xlabel('Kilometraje')
plt.ylabel('Frecuencia')
plt.show()


# Elimina la puntuación de la columna de precios
ventas_autos['Precio (USD)'] = ventas_autos['Precio (USD)'].str.replace('[\,\$\.]', '', regex=True).astype(float)

# Intentamos graficar la columna de precios
ventas_autos['Precio (USD)'].plot()
plt.title('Precios de Vehículos')
plt.ylabel('Precio')
plt.xlabel('Índice')
plt.show()
